# The Woman Named *Wisdom* Calls Out

## Proverbs 8:1-5

> Doesn’t wisdom cry out?  
> Doesn’t understanding raise her voice?  
> On the top of high places by the way,  
> where the paths meet, she stands.  
> Beside the gates, at the entry of the city,  
> at the entry doors, she cries aloud:  
> “I call to you men!  
> I send my voice to the sons of mankind.  
> You simple, understand prudence!  
> You fools, be of an understanding heart!  

**Questions to consider**

- What is Wisdom doing? Why?
- Where is she calling out?
- Who is she calling out to?
- What does *naive* mean?
  - *(of a person or action) showing a lack of experience, wisdom, or judgment*
- What does *prudence* mean?
  - *acting with or showing care and thought for the future*

This year Daddy wants to study the Proverbs together. Why? Because I want you children to be wise and not foolish. A wise man or woman will be protected and will be a blessing to everyone around him. But a foolish man will destroy himself and the people closest to him. 

God has given us this book of Proverbs to teach us how to be wise. So we should read it and study it carefully.

*Monday, August 17, 2020*

------------------

## *Proverbs 8:6-11*

> Hear, for I will speak excellent things.  
> The opening of my lips is for right things.  
> For my mouth speaks truth.  
> Wickedness is an abomination to my lips.  
> All the words of my mouth are in righteousness.  
> There is nothing crooked or perverse in them.  
> They are all plain to him who understands,  
> right to those who find knowledge.  
> Receive my instruction rather than silver,  
> knowledge rather than choice gold.  
> For wisdom is better than rubies.  
> All the things that may be desired can’t be compared to it.  

**Questions to consider**

- Why do we have to be told to listen? Do we like to hear the truth?
- Can you be good without telling the truth? Can you tell the truth and be wicked?
- What is the difference between wisdom and knowledge?
- How valuable is the truth? How valuable is wisdom?

We must be exhorted to listen because we don't want to. We like to tell ourselves lies, and we often like to listen to other people tell us lies. Some people whant to separate goodness from truthfulness. They say you can speak lies but still be good. That's a lie. God is Righteous **and** True. There is no separating those two characteristics with Him.

*Tuesday, August 18, 2020*

------------------

## Proverbs 8:12-13

> 12 “I, wisdom, have made prudence my dwelling.  
> Find out knowledge and discretion.  
> 13 The fear of Yahweh is to hate evil.  
> I hate pride, arrogance, the evil way, and the perverse mouth.  

**Questions to consider**

- What does *prudence* mean, again?
  - Remember that *prudence* means, *acting with or showing care and thought for the future*.
- We had a conversation yesterday about the importance of delayed gratification. What does delayed gratification have to do with prudence?
- What does it mean for wisdom to have a home in "prudence?"
- What does *discretion* mean? Why is it important?
	- *Discretion* means acting or speaking in a way that avoids causing offense or revealing private information.
- What things do you hate?
- Do you naturally hate evil? Or do you have have to learn to hate evil?
- What is the fear of the Lord/Yahweh? Why is does hating evil show that you fear the Lord?
- What does God hate?

To learn wisdom, we must learn all three things: how to think, how to talk, and how to act. We must have our emotions trained *as well as* our minds. There is no separating the two of them, no matter how hard we might try.

*Wednesday, August 19, 2020*

------------------

## Proverbs 8:14-21

> 14 Counsel and sound knowledge are mine.  
> I have understanding and power.  
> 15 By me kings reign,  
> and princes decree justice.  
> 16 By me princes rule,  
> nobles, and all the righteous rulers of the earth.  
> 17 I love those who love me.  
> Those who seek me diligently will find me.  
> 18 With me are riches, honor,  
> enduring wealth, and prosperity.  
> 19 My fruit is better than gold, yes, than fine gold,  
> my yield than choice silver.  
> 20 I walk in the way of righteousness,  
> in the middle of the paths of justice,  
> 21 that I may give wealth to those who love me.  
> I fill their treasuries.  

**Questions to consider**

It has been a few days since we started this chapter, so let's try to remember a few things:

- Who is speaking in this chapter, Proverbs chapter 8?
- Why is she speaking? Generally, what is she trying to say?
- Lady wisdom claims to have many things in these verses. Can you tell me what some of them are?
- So does wisdom help you get to heaven, or does it just help you gain riches and wealth here on earth? (hint: that's a bad question...)
- Have you ever heard of the "health and wealth gospel?" What is it? What does that phrase mean?

If we are wise, we can usually expect the fruit of our work and life to be good - both here on earth and on heaven. But an essential part of wisdom is to not confuse the blessings of this life with the final blessings of heaven.

*Thursday, August 20, 2020*

------------------

## Proverbs 8:22-31

22 “Yahweh possessed me in the beginning of his work,  
before his deeds of old.  
23 I was set up from everlasting, from the beginning,  
before the earth existed.  
24 When there were no depths, I was born,  
when there were no springs abounding with water.  
25 Before the mountains were settled in place,  
before the hills, I was born;  
26 while as yet he had not made the earth, nor the fields,  
nor the beginning of the dust of the world.  
27 When he established the heavens, I was there.  
When he set a circle on the surface of the deep,  
28 when he established the clouds above,  
when the springs of the deep became strong,  
29 when he gave to the sea its boundary,  
that the waters should not violate his commandment,  
when he marked out the foundations of the earth,  
30 then I was the craftsman by his side.  
I was a delight day by day,  
always rejoicing before him,  
31 rejoicing in his whole world.  
My delight was with the sons of men.  

**Questions to consider**

- When did God create wisdom?
- Why is it important that wisdom came before everything else?
	- It shows that wisdom is more foundational, important and essential. Wisdom has authority - it has a right to speak.
- Matthew Henry thinks that Solomon is referring to Jesus Christ here. As it says in 1 Cor. 1:24: "...but to those who are called, both Jews and Greeks, Christ is the power of God and the wisdom of God;"

*Friday, August 21, 2020*

------------------

## Proverbs 

*Monday, August 24, 2020*

------------------

## Proverbs 2:1-5

> 1 My son, if you will receive my words,  
> and store up my commandments within you,  
> 2 so as to turn your ear to wisdom,  
> and apply your heart to understanding;  
> 3 yes, if you call out for discernment,  
> and lift up your voice for understanding;  
> 4 if you seek her as silver,  
> and search for her as for hidden treasures;  
> 5 then you will understand the fear of Yahweh,  
> and find the knowledge of God.  


*Tuesday, August 25, 2020 (Asher's birthday)*

------------------

## Proverbs 4:14-19
  
> 14 Don’t enter into the path of the wicked.  
> Don’t walk in the way of evil men.  
> 15 Avoid it, and don’t pass by it.  
> Turn from it, and pass on.  
> 16 For they don’t sleep unless they do evil.  
> Their sleep is taken away, unless they make someone fall.  
> 17 For they eat the bread of wickedness  
> and drink the wine of violence.  
> 18 But the path of the righteous is like the dawning light  
> that shines more and more until the perfect day.  
> 19 The way of the wicked is like darkness.  
> They don’t know what they stumble over.  

**Questions to consider**

- Don't walk here, walk here.
- Why wouldn't someone be able to sleep until they do evil?
- Eat bread and drink wine... what does that remind you of? And what does communion signify?
- The righteous gets increasingly clear and bright.
- And darkness? Confusion?

*Friday, August 28, 2020*

------------------

## Proverbs 1:1-6
  
> 1 The proverbs of Solomon, the son of David, king of Israel:    
> 2 to know wisdom and instruction;    
> to discern the words of understanding;    
> 3 to receive instruction in wise dealing,    
> in righteousness, justice, and equity;    
> 4 to give prudence to the simple,    
> knowledge and discretion to the young man—    
> 5 that the wise man may hear, and increase in learning;    
> that the man of understanding may attain to sound counsel;    
> 6 to understand a proverb and parables,    
> the words and riddles of the wise.    

-------

## Proverbs 1:8-9

> 8 My son, listen to your father’s instruction,  
> and don’t forsake your mother’s teaching;  
> 9 for they will be a garland to grace your head,  
> and chains around your neck.  

## Proverbs 2:1-10

> 1 My son, if you will receive my words,  
> and store up my commandments within you,  
> 2 so as to turn your ear to wisdom,  
> and apply your heart to understanding;  
> 3 yes, if you call out for discernment,  
> and lift up your voice for understanding;  
> 4 if you seek her as silver,  
> and search for her as for hidden treasures;  
> 5 then you will understand the fear of Yahweh,  
> and find the knowledge of God.*  
> 6 For Yahweh gives wisdom.  
> Out of his mouth comes knowledge and understanding.  
> 7 He lays up sound wisdom for the upright.  
> He is a shield to those who walk in integrity,  
> 8 that he may guard the paths of justice,  
> and preserve the way of his saints.  
> 9 Then you will understand righteousness and justice,  
> equity and every good path.  
> 10 For wisdom will enter into your heart.  
> Knowledge will be pleasant to your soul.  

**Questions to Consider:**

- Who gives you instruction? Why is the instruction of your mother and father so important?
- What is a garland?
- Do you like hidden treasure? If you knew there was hidden treasure at the church, what would you do?
- What is the promise we have if we seek for wisdom? *(That we will find it!)* Where does wisdom come from?
- What is one of the benefits of having wisdom? *(That our integrity and righteousness will protect us.)*
- Is knowledge always pleasant to our souls? Why or why not?